### ISSUE TITLE
Deploy MVP on github pages and point ehtereum.brightid.org to it

### ISSUE THREAD

**Issue by Tomasvrba** [BurnerVote/BurnerVoteSpec#7]
For MVP deployment, let's use github pages to make it quick.

- [x] Activate github pages to deploy MVP (@Tomasvrba)
- [x] Point ethereum.brightid.org to it once the above is ready (@adamstallard)

**Comment by Tomasvrba** [comment]
@adamstallard the gh-pages deployment is ready here: https://burnsignal.github.io/BrightID-EthereumAddressService/
I can change the domain to ethereum.brightid.org whenver you say it's ready.

**Comment by adamstallard** [comment]
Ok I set up the CNAME.  ethereum.brightid.org is an alias of burnsignal.github.io

Please review

**Comment by Tomasvrba** [comment]
> Ok I set up the CNAME. ethereum.brightid.org is an alias of burnsignal.github.io
> 
> Please review

Awesome, thanks! 
Just changed the URL and redeployed. It's live here: https://ethereum.brightid.org

**Comment by Tomasvrba** [comment]
Resolved with: https://github.com/burnSignal/BrightID-EthereumAddressService/pull/5 and https://github.com/burnSignal/BrightID-EthereumAddressService/pull/6
